---
title: "Trafikkregistreringer i Mjøsbyen"
format: 
  html:
    css: svv.css
    number-sections: true
    toc: true
    toc-location: left
    df-print: paged
editor: source
knitr: 
  opts_chunk: 
    echo: false
---

```{r}
#| label: read

library(DT)

trp_info_mjosbyen <- 
  readr::read_rds(
  file = "trp_mjosbyen.rds"
)
```

# Bakgrunn

Her presenteres en oversikt over trafikkregistreringene i Mjøsbyen. Les om området her: <https://www.mjosbyen.no/hva-er-mjosbyen/>.

# Trafikkregistreringer

En liste over alle trafikkregistreringspunkter i området er gitt i tabellen nedenfor.

```{r}
#| label:  table

trp_info_mjosbyen |> 
  dplyr::select(
    Punkt = name,
    Veg = road_category_and_number,
    Kommune = municipality_name,
    Oppstart = first_data_with_quality_metrics,
    Siste = latest_daily_traffic
  ) |> 
  dplyr::mutate(
    Oppstart = as.character(Oppstart)
  ) |> 
  DT::datatable(
    filter = "top",
    extensions = "Buttons",
    rownames = FALSE,
    options = list(
      dom = "Blfrtip",
      #buttons = c("excel"),
      pageLength = 15,
      lengthMenu = c(15, 50, 100),
      autoWidth = TRUE))
```

